package main

// Environment variables
var CONFIGURE_ONLY = "GOWLLVM_CONFIGURE_ONLY"
var COMPILER_PATH = "GOWLLVM_COMPILER_PATH"
var C_COMPILER_NAME = "GOWLLVM_CC_NAME"
var CXX_COMPILER_NAME = "GOWLLVM_CXX_NAME"
var BC_STORE_PATH = "GOWLLVM_BC_STORE"

// Gowllvm functioning
var ELF_SECTION_NAME = ".llvm_bc"
var DARWIN_SEGMENT_NAME = "__WLLVM"
var DARWIN_SECTION_NAME = "__llvm_bc"
