name: Go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.16

    - name: Install LLVM
      run: sudo apt-get install -y clang llvm

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./tests
